# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.chat/configuration/

[font]
family = "TX-02"
size = 20

[servers.liberachat]
nickname = "aria-coffee"
nick_password_command = "op read \"op://Personal/3d3jcravcmuyn4edal33growyy/password\""
server = "irc.libera.chat"
channels = ["#halloy"]

[servers.rizon]
nickname = "aria-coffee"
nick_password_command = "op read \"op://Personal/5erb73jgzalyuwjvrckdsgrdmy/password\""
server = "irc.rizon.net"
channels = ["#judgment", "Global"]
